### ISSUE TITLE
Plugin Not working - Synology WEBDAV  ERROR - Error while calling plugin webdavbackup

### ISSUE THREAD

**Issue by ingo916** [edekeijzer/OctoPrint-WebDavBackup#10]
OctoPrint 1.5.3
    Python 3.7.3
    OctoPi 0.18.0

Log snippet
2021-01-26 21:30:43,923 - octoprint.plugins.webdavbackup - INFO - Backup /home/pi/.octoprint/data/backup/octoprint-backup-20210126-213043.zip created, will now attempt to upload to http://x.x.x.x:5005/OctoPrint_Backups/Ender_3_v2/
2021-01-26 21:30:58,545 - octoprint.plugin - ERROR - Error while calling plugin webdavbackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/__init__.py", line 71, in on_event
    _recursive_create_path(upload_path)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/__init__.py", line 68, in _recursive_create_path
    _recursive_create_path(os.path.abspath(os.path.join(path, "..")))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/__init__.py", line 68, in _recursive_create_path
    _recursive_create_path(os.path.abspath(os.path.join(path, "..")))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/__init__.py", line 68, in _recursive_create_path
    _recursive_create_path(os.path.abspath(os.path.join(path, "..")))
  [Previous line repeated 960 more times]
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/__init__.py", line 64, in _recursive_create_path
    if davclient.check(path):
  File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 66, in _wrapper
    res = fn(self, *args, **kw)
  File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 292, in check
    response = self.execute_request(action='check', path=urn.quote())
  File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 217, in execute_request
    verify=self.verify
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/oprint/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,

**Comment by edekeijzer** [comment]
This is the same issue as #4 
Currently looking into this.
