### ISSUE TITLE
Not working on OctoPrint 1.5.2 Python 3.7.3 OctoPi 0.17.0

### ISSUE THREAD

**Issue by ZeekWorld** [edekeijzer/OctoPrint-WebDavBackup#3]
Installed plugin via URL.
Message shows as successful.
Reload.
Plugin is not listed, nor shows on the plugin manager.

**Comment by mrwsl** [comment]
To give some more feedback from the logs:

```
ERROR - Error loading plugin webdavbackup
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 1298, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 69, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_webdavbackup/__init__.py", line 6, in <module>
    from webdav3.client import Client
  File "/home/pi/oprint/lib/python3.7/site-packages/webdav3/client.py", line 12, in <module>
    import lxml.etree as etree
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory
```

EDIT: Which can be solved by `apt-get install libxslt-dev`.

**Comment by Lecl0ne** [comment]
Exactly the same here.

**Comment by edekeijzer** [comment]
I'll try to find a Raspberry Pi to install OctoPi and look into this.

**Comment by edekeijzer** [comment]
I've finally been able to look into this. The issue never appeared while testing my plugin on the Docker image. It seems that for amd64 there is n installable package available for lxml, but for ARM (Raspberry Pi) there isn't, so it has to be compiled from source which requires the libxml2-dev and libxslt-dev packages to be installed.
There's no way to really fix this for me, but I will put the dev packages into the requirements list.

**Comment by Lecl0ne** [comment]
So we just have to install this packages?

**Comment by ZeekWorld** [comment]
So you mean there is no way to make it work on octopi?? 
Ok, signing off then. Thanks.
